const REQUIRED=["schema","id","name","version","base","identity"];
const DISTROS=new Set(["linuxmint","debian","ubuntu","fedora","arch","none"]);
function parseMaybeYaml(text){try{return JSON.parse(text)}catch(_){}
const data={};let key=null,buf=[];const take=()=>{if(!key)return;const raw=buf.join("\n").trim();if(raw.startsWith("|")||raw.startsWith(">"))data[key]=raw.replace(/^[|>]\s*/,"");else if(raw.startsWith("- "))data[key]=raw.split(/\n- /).map(s=>s.replace(/^- /,""));else data[key]=raw};
for(const line of text.split(/\r?\n/)){if(/^[a-zA-Z0-9_]+:/.test(line)&&!line.startsWith(" ")){take();const i=line.indexOf(":");key=line.slice(0,i);buf=[line.slice(i+1)]}else buf.push(line)}take();if(typeof data.base==="string")data.base={distro:data.base};return data}
function validateFlavor(data){const errors=[];if(!data||typeof data!=="object")return["document is not an object"];for(const k of REQUIRED)if(!(k in data))errors.push("missing "+k);if(data.schema&&data.schema!=="harbor-flavor/v1")errors.push("schema must be harbor-flavor/v1");const distro=data.base&&data.base.distro;if(distro&&!DISTROS.has(distro))errors.push("unsupported base.distro: "+distro);const id=data.identity||{};if(data.identity&&(!id.os_name||!id.codename))errors.push("identity needs os_name and codename");const blob=JSON.stringify(data).toLowerCase();for(const secret of ["api_key","xai_api_key","begin rsa private","sk-"])if(blob.includes(secret))errors.push("possible secret material: "+secret);if(/\bofficial (xai|grok) os\b/.test(blob))errors.push("community flavors may not claim official xAI status");return errors}
function card(item,official){const el=document.createElement("article");el.className="flavor";el.innerHTML=`<div class="meta">${official?"Official":"Community"} · ${item.version||""} · <span class="risk ${item.risk||"unsigned"}">${item.risk||"unsigned"}</span></div><h3>${item.name}</h3><p class="lead">${item.summary||""}</p><div class="row">${item.download?`<a class="btn" href="${item.download}">Download</a>`:""}${item.source?`<a class="btn ghost" href="${item.source}">Source</a>`:""}${item.flavor?`<a class="btn ghost" href="../${item.flavor}">Flavor file</a>`:""}</div>`;return el}
async function loadCatalog(){let catalog=null;try{const res=await fetch("catalog.json",{cache:"no-store"});if(res.ok)catalog=await res.json()}catch(_){}
if(!catalog){catalog={official:[{id:"zen-garden",name:"FreshOS Zen Garden Edition",version:"1.0.0",download:"https://github.com/djlacavera21/harbor-os/archive/refs/heads/main.zip",source:"https://github.com/djlacavera21/harbor-os",flavor:"flavors/zen-garden/harbor.flavor.yaml",risk:"low",summary:"Mint overlay, Zen Garden visualizer, optional Grok Zen Master."}],community:[]}}
const og=document.getElementById("official-grid");const fg=document.getElementById("flavor-grid");og.innerHTML="";fg.innerHTML="";(catalog.official||[]).forEach(i=>og.appendChild(card(i,true)));const community=catalog.community||[];(catalog.official||[]).concat(community).forEach(i=>fg.appendChild(card(i,(catalog.official||[]).some(o=>o.id===i.id))));if(!community.length){const note=document.createElement("p");note.className="lead";note.textContent="No reviewed community flavors in the catalog yet.";fg.appendChild(note)}}
document.querySelectorAll(".tab").forEach(btn=>btn.addEventListener("click",()=>{const id=btn.dataset.tab;document.querySelectorAll("section").forEach(s=>s.classList.toggle("active",s.id===id));document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.tab===id))}));
const premium=document.getElementById("premium"),file=document.getElementById("file"),yaml=document.getElementById("yaml"),validateBtn=document.getElementById("validate"),packetBtn=document.getElementById("packet"),log=document.getElementById("log");
function setGate(on){[file,yaml,validateBtn,packetBtn].forEach(el=>el.disabled=!on);log.textContent=on?"Gate open (local Premium+ simulation). Validate before you submit a PR.":"Gate closed. Enable Premium+ simulation to upload."}
premium.addEventListener("change",()=>setGate(premium.checked));
file.addEventListener("change",async()=>{const f=file.files[0];if(!f)return;if(f.size>50*1024*1024){log.innerHTML='<span class="bad">File exceeds 50 MiB community cap.</span>';return}if(/\.(iso|img)$/i.test(f.name)){log.innerHTML='<span class="bad">ISO / disk images are forbidden in flavor packs.</span>';return}yaml.value=await f.text();log.textContent="Loaded "+f.name+" ("+f.size+" bytes)"});
function currentDoc(){const text=yaml.value.trim();if(!text)return{errors:["nothing to validate"],data:null,text};try{const data=parseMaybeYaml(text);return{errors:validateFlavor(data),data,text}}catch(e){return{errors:["parse failed: "+e.message],data:null,text}}}
validateBtn.addEventListener("click",()=>{const{errors,data}=currentDoc();log.innerHTML=errors.length?'<span class="bad">INVALID</span>\n'+errors.map(e=>"  - "+e).join("\n"):'<span class="ok">VALID '+data.id+"@"+data.version+" ("+data.name+")</span>"});
packetBtn.addEventListener("click",()=>{const{errors,data,text}=currentDoc();if(errors.length){log.innerHTML='<span class="bad">Fix validation first.</span>\n'+errors.map(e=>"  - "+e).join("\n");return}const packet={schema:"harbor-experimentals-submission/v1",proposed_gate:"X Premium+",submitted_at:new Date().toISOString(),flavor:data,catalog_patch:{community:[{id:data.id,name:data.name,version:data.version,channel:"community",risk:"unsigned",min_subscription:"none",summary:data.summary||"",flavor:"flavors/"+data.id+"/harbor.flavor.yaml"}]},publish_via:"https://github.com/djlacavera21/harbor-os/compare"};const blob=new Blob([JSON.stringify(packet,null,2)+"\n\n--- flavor ---\n"+text],{type:"text/plain"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=data.id+".harbor-submission.txt";a.click();log.innerHTML='<span class="ok">Packet ready.</span> Open a PR that adds flavors/'+data.id+"/harbor.flavor.yaml and catalog.community[]."});
loadCatalog();
